/* Paid Membership Manager — local-first membership database and UI. */
const PLANS = {"1 Month": [5000,1],"3 Months": [12000,3],"6 Months": [24000,6],"9 Months": [36000,9],"12 Months": [48000,12],"Lifetime": [55000,null]};
const PRODUCTS = ["Doujinshi Paid","Manhwa Paid"], PAYMENTS = ["KPay","Wave Pay","Aya Pay"];
const KEY = "paidMembershipManager_v1";
let members = JSON.parse(localStorage.getItem(KEY) || "[]"), charts = {};
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const fmt = n => new Intl.NumberFormat("en-US").format(n || 0) + " Ks";
const localDate = d => new Date(d + "T00:00:00");
const dateKey = d => { const x = new Date(d); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`; };
const today = () => dateKey(new Date());
function prettyDate(v){ if(!v) return "Never expires"; return localDate(v).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}); }
function save(){ localStorage.setItem(KEY, JSON.stringify(members)); }
function statusOf(m){ if(m.plan === "Lifetime") return "Lifetime"; return m.expireDate < today() ? "Expired" : "Active"; }
function syncStatuses(){ members.forEach(m => m.status = statusOf(m)); save(); }
function sums(list){ return list.reduce((a,m)=>a+m.price,0); }
function byName(list, key, values){ return Object.fromEntries(values.map(v=>[v,list.filter(x=>x[key]===v)])); }
function makeId(){ return crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2); }
function toast(message){ const t=$("#toast");t.textContent=message;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),2800); }
function addMonths(start, months){ const d=localDate(start); const day=d.getDate(); d.setMonth(d.getMonth()+months); if(d.getDate()!==day) d.setDate(0); return dateKey(d); }
function renderCards(target, data){ $(target).innerHTML=data.map((x,i)=>`<article class="stat-card" style="--card-glow:${["#dce5ff","#e9ddff","#d8f4e8"][i%3]}"><span class="stat-label">${x.label}</span><strong class="stat-value">${x.value}</strong>${x.sub?`<span class="stat-sub">${x.sub}</span>`:""}</article>`).join(""); }
function detailRows(target, groups, total){ $(target).innerHTML=Object.entries(groups).map(([name,list])=>`<div class="detail-row"><div><strong>${name}</strong><div class="member-meta">${list.length} member${list.length===1?"":"s"}</div></div><strong>${fmt(sums(list))}</strong></div>`).join(""); }
function renderDashboard(){ syncStatuses(); const active=members.filter(m=>m.status==="Active"), expired=members.filter(m=>m.status==="Expired"), lifetime=members.filter(m=>m.status==="Lifetime"); const joinedToday=members.filter(m=>m.startDate===today()); const now=new Date(), monthMembers=members.filter(m=>{let d=localDate(m.startDate);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});
 renderCards("#revenueStats",[{label:"Total revenue",value:fmt(sums(members)),sub:`${members.length} member records`},{label:"Today revenue",value:fmt(sums(joinedToday)),sub:`${joinedToday.length} joined today`},{label:"Monthly revenue",value:fmt(sums(monthMembers)),sub:`${monthMembers.length} joins this month`}]);
 $("#membershipStats").innerHTML=[["Total members",members.length],["Active members",active.length],["Expired members",expired.length],["Lifetime members",lifetime.length]].map(x=>`<div class="mini-stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");
 const upcoming=active.filter(m=>{let days=(localDate(m.expireDate)-localDate(today()))/86400000;return days>=0&&days<=7}).sort((a,b)=>a.expireDate.localeCompare(b.expireDate)); $("#expiringList").innerHTML=upcoming.length?upcoming.map(m=>`<div class="expiry-item"><div><div class="member-name">${escapeHtml(m.username)}</div><div class="member-meta">${m.product} · ${m.plan}</div></div><span class="chip accent">${prettyDate(m.expireDate)}</span></div>`).join(""):'<div class="empty">No memberships expire in the next 7 days.</div>';
 const plans=byName(members,"plan",Object.keys(PLANS)), max=Math.max(1,...Object.values(plans).map(x=>x.length)); $("#planStats").innerHTML=Object.entries(plans).map(([name,list])=>`<div class="plan-row"><span>${name}</span><div class="plan-bar" style="width:${(list.length/max)*100}%"></div><span>${list.length}</span></div>`).join("");
 detailRows("#productStats",byName(members,"product",PRODUCTS)); detailRows("#paymentStats",byName(members,"payment",PAYMENTS)); renderCharts(); }
function renderCharts(){ if(!window.Chart) return; const text=getComputedStyle(document.body).getPropertyValue("--muted").trim(), grid=getComputedStyle(document.body).getPropertyValue("--line").trim(); Object.values(charts).forEach(c=>c.destroy()); const labels=[], data=[]; for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let key=dateKey(d);labels.push(d.toLocaleDateString("en-US",{weekday:"short"}));data.push(sums(members.filter(m=>m.startDate===key)));} charts.revenue=new Chart($("#revenueChart"),{type:"line",data:{labels,datasets:[{data,borderColor:"#5b78ff",backgroundColor:"rgba(91,120,255,.12)",fill:true,tension:.45,pointRadius:3,pointBackgroundColor:"#5b78ff"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmt(c.raw)}},},scales:{x:{grid:{display:false},ticks:{color:text}},y:{border:{display:false},grid:{color:grid},ticks:{color:text,callback:v=>v/1000+"k"}}}}}); const doughnut=(el,vals)=>new Chart($(el),{type:"doughnut",data:{labels:vals.map(x=>x[0]),datasets:[{data:vals.map(x=>x[1]),backgroundColor:["#5b78ff","#a684f6","#43c597"],borderWidth:0,hoverOffset:5}]},options:{responsive:true,maintainAspectRatio:false,cutout:"68%",plugins:{legend:{position:"bottom",labels:{color:text,boxWidth:9,padding:15,font:{size:11}}}}}}); charts.product=doughnut("#productChart",PRODUCTS.map(p=>[p,members.filter(m=>m.product===p).length]));charts.payment=doughnut("#paymentChart",PAYMENTS.map(p=>[p,sums(members.filter(m=>m.payment===p))])); }
function escapeHtml(v){const d=document.createElement("div");d.textContent=v||"";return d.innerHTML;}
function renderMembers(){ let list=[...members], q=$("#memberSearch").value.trim().toLowerCase(), product=$("#productFilter").value,status=$("#statusFilter").value,sort=$("#sortMembers").value; if(q)list=list.filter(m=>m.username.toLowerCase().includes(q));if(product)list=list.filter(m=>m.product===product);if(status)list=list.filter(m=>m.status===status); list.sort((a,b)=>sort==="name"?a.username.localeCompare(b.username):sort==="oldest"?a.createdAt.localeCompare(b.createdAt):b.createdAt.localeCompare(a.createdAt)); $("#membersTable").innerHTML=list.length?list.map(m=>`<tr><td><strong>${escapeHtml(m.username)}</strong></td><td>${m.product.replace(" Paid","")}</td><td>${m.plan}</td><td>${fmt(m.price)}</td><td>${m.payment}</td><td>${prettyDate(m.startDate)}</td><td>${prettyDate(m.expireDate)}</td><td><span class="status ${m.status.toLowerCase()}">${m.status}</span></td><td class="notes-cell" title="${escapeHtml(m.notes)}">${escapeHtml(m.notes)||"—"}</td><td><button class="icon-btn edit-btn" data-id="${m.id}" title="Edit">✎</button><button class="icon-btn delete-btn" data-id="${m.id}" title="Delete">⌫</button></td></tr>`).join(""):'<tr><td colspan="10"><div class="empty">No members match your filters.</div></td></tr>'; }
function renderReports(){const now=new Date(), daily=members.filter(m=>m.startDate===today()), monthly=members.filter(m=>{const d=localDate(m.startDate);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}); $("#dailyReportDate").textContent=now.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"});$("#monthlyReportDate").textContent=now.toLocaleDateString("en-US",{month:"long",year:"numeric"}); renderCards("#dailyReportStats",[{label:"Members joined",value:daily.length},{label:"Total revenue",value:fmt(sums(daily))},{label:"Average purchase",value:fmt(daily.length?sums(daily)/daily.length:0)}]); renderCards("#monthlyReportStats",[{label:"Total members",value:monthly.length},{label:"Total revenue",value:fmt(sums(monthly))},{label:"Lifetime purchases",value:monthly.filter(m=>m.plan==="Lifetime").length}]); detailRows("#dailyProducts",byName(daily,"product",PRODUCTS));detailRows("#dailyPayments",byName(daily,"payment",PAYMENTS));detailRows("#monthlyProducts",byName(monthly,"product",PRODUCTS));detailRows("#monthlyPayments",byName(monthly,"payment",PAYMENTS));}
function refresh(){ renderDashboard();renderMembers();renderReports(); }
function openModal(member){ $("#memberForm").reset(); $("#memberId").value=member?.id||"";$("#modalTitle").textContent=member?"Edit member":"Add member";$("#modalEyebrow").textContent=member?"Update subscription":"New subscription";["username","product","plan","payment","startDate","notes"].forEach(k=>{if(member)$("#"+k).value=member[k]});if(!member){$("#startDate").value=today();$("#plan").value="1 Month"} updatePlanFields();$("#memberModal").classList.add("show"); $("#memberModal").setAttribute("aria-hidden","false"); }
function closeModal(){ $("#memberModal").classList.remove("show");$("#memberModal").setAttribute("aria-hidden","true"); }
function updatePlanFields(){const [price,months]=PLANS[$("#plan").value];$("#price").value=fmt(price);$("#expireDate").value=months?addMonths($("#startDate").value||today(),months):"Never Expire";}
function csvDownload(filename, rows){const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8;"}));a.download=filename;a.click();URL.revokeObjectURL(a.href);}
function exportMembers(){csvDownload("paid-members-"+today()+".csv",[["Username","Product","Plan","Price (Ks)","Payment","Start Date","Expire Date","Status","Notes"],...members.map(m=>[m.username,m.product,m.plan,m.price,m.payment,m.startDate,m.expireDate||"Never Expire",m.status,m.notes])]);toast("Members exported as CSV.");}
function exportReport(type){const now=new Date(),list=type==="daily"?members.filter(m=>m.startDate===today()):members.filter(m=>{const d=localDate(m.startDate);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});csvDownload(`${type}-report-${today()}.csv`,[[`${type.toUpperCase()} REPORT`],["Total members",list.length],["Total revenue (Ks)",sums(list)],[],["Product","Members","Revenue (Ks)"],...PRODUCTS.map(p=>{let l=list.filter(m=>m.product===p);return[p,l.length,sums(l)]}),[],["Payment","Members","Revenue (Ks)"],...PAYMENTS.map(p=>{let l=list.filter(m=>m.payment===p);return[p,l.length,sums(l)]})]);toast(`${type[0].toUpperCase()+type.slice(1)} report exported.`);}
function init(){ $("#plan").innerHTML=Object.keys(PLANS).map(p=>`<option>${p}</option>`).join("");$("#todayDate").textContent=new Date().toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"});$("#greeting").textContent=new Date().getHours()<12?"Good morning":new Date().getHours()<18?"Good afternoon":"Good evening";const dark=localStorage.getItem("pmm_theme")==="dark";document.body.classList.toggle("dark",dark);updateThemeText();refresh();
 $$(".nav-link[data-page]").forEach(b=>b.onclick=()=>{ $$(".nav-link").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".page").forEach(p=>p.classList.toggle("active",p.id===b.dataset.page));$("#pageTitle").textContent=b.textContent.trim();$("#sidebar").classList.remove("open"); });$("#mobileMenu").onclick=()=>$("#sidebar").classList.toggle("open");$("#addMemberBtn").onclick=()=>openModal();$("#closeModal").onclick=closeModal;$("#cancelModal").onclick=closeModal;$("#memberModal").onclick=e=>{if(e.target===$("#memberModal"))closeModal()};$("#plan").onchange=updatePlanFields;$("#startDate").onchange=updatePlanFields;
 $("#memberForm").onsubmit=e=>{e.preventDefault();const id=$("#memberId").value, plan=$("#plan").value,[price,months]=PLANS[plan],old=members.find(m=>m.id===id),m={id:id||makeId(),username:$("#username").value.trim(),product:$("#product").value,plan,price,payment:$("#payment").value,startDate:$("#startDate").value,expireDate:months?addMonths($("#startDate").value,months):null,status:"Active",notes:$("#notes").value.trim(),createdAt:old?.createdAt||new Date().toISOString()};m.status=statusOf(m);if(id)members=members.map(x=>x.id===id?m:x);else members.unshift(m);save();closeModal();refresh();toast(id?"Member updated.":"Member added.");};["memberSearch","productFilter","statusFilter","sortMembers"].forEach(id=>$("#"+id).addEventListener(id==="memberSearch"?"input":"change",renderMembers));$("#membersTable").onclick=e=>{let id=e.target.dataset.id;if(e.target.classList.contains("edit-btn"))openModal(members.find(m=>m.id===id));if(e.target.classList.contains("delete-btn")&&confirm("Delete this member record?")){members=members.filter(m=>m.id!==id);save();refresh();toast("Member deleted.")}};$("#exportMembersBtn").onclick=exportMembers;$$(".report-export").forEach(b=>b.onclick=()=>exportReport(b.dataset.report));$("#backupBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(members,null,2)],{type:"application/json"}));a.download="paid-members-backup-"+today()+".json";a.click();URL.revokeObjectURL(a.href);toast("Backup downloaded.")};$("#restoreInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data))throw Error();if(confirm(`Restore ${data.length} member records? This replaces current data.`)){members=data.map(m=>({...m,status:statusOf(m)}));save();refresh();toast("Backup restored.")}}catch{toast("That JSON backup could not be read.")}e.target.value=""};$("#themeToggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("pmm_theme",document.body.classList.contains("dark")?"dark":"light");updateThemeText();renderCharts()};}
function updateThemeText(){$("#themeText").textContent=document.body.classList.contains("dark")?"Light appearance":"Dark appearance";$("#themeIcon").textContent=document.body.classList.contains("dark")?"☀":"◐";}document.addEventListener("DOMContentLoaded",init);
